name: auto-approve

on:
  pull_request_target:
    types: [ labeled, unlabeled, opened, synchronize, reopened, ready_for_review, review_requested ]

jobs:
  auto-approve:

    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'auto-approve')
    
    steps:
    - uses: hmarr/auto-approve-action@v2
      with: 
        github-token: "${{ secrets.GITHUB_TOKEN }}"
