name: npm-upgrade

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch: {}

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - run: npx npm-check-updates -u
    - run: npm install
    - run: |-
        git add .
        git diff --patch --staged > ${{ runner.temp }}/upgrade.patch
    - uses: actions/upload-artifact@v3
      with:
        name: upgrade.patch
        path: ${{ runner.temp }}/upgrade.patch

  create-pr:
    needs: upgrade
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: upgrade.patch
        path: ${{ runner.temp }}
    - run: '[ -s ${{ runner.temp }}/upgrade.patch ] && git apply ${{ runner.temp
          }}/upgrade.patch || echo "Empty patch. Skipping."'
    - uses: peter-evans/create-pull-request@v4.1.3
      with:
        branch: workflows/npm-upgrade
        commit-message: "update npm dependencies"
        labels: auto
        title: Update npm dependencies
        token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
